### ISSUE TITLE
Serving static files in DEBUG=FALSE

### ISSUE THREAD

**Issue by aaronoppenheimer** [Gig-o-Matic/GO3#109]
In production will have to work out how static files are served.

https://docs.djangoproject.com/en/3.0/howto/static-files/deployment/

**Comment by aaronoppenheimer** [comment]
don't forget to look at custom 404 page too

**Comment by bklang** [comment]
It looks like the custom 404 (and 500) pages were handled in #199.

Serving static assets will be handled in #211
