### ISSUE TITLE
Calendar subscription instructions missing

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#210]
It appears that the calendar subscription instructions were lost in the Django port. The view at `/help/calfeed/1` has translation placeholders like `calhelp_1` and `calhelp_2` which do not appear to be defined anywhere. Maybe these can be lifted from GO2?

<img width="1097" alt="Screenshot 2024-02-25 at 11 51 50 AM" src="https://github.com/Gig-o-Matic/GO3/assets/167131/b9588528-9772-41d8-9be9-34bb28527ab4">

**Comment by bklang** [comment]
Text lifted from [the live site](https://www.gig-o-matic.com/calhelp):


Calendar Help!
The Gig-o-Matic can provide calendar information to Google Calendar, Apple Calendar, and other calendar tools that work with the "CalDav" protocol. Here's how to do it!

First, copy the subscription address. Your personalized address is:

http://www.gig-o-matic.com/cal/m/ag1zfmdpZy1vLW1hdGljchMLEgZNZW1iZXIYgICA6P_XlQsM

Subscribing in Google Calendar: In the "Other Calendars" menu select "Add by URL" - paste the calendar address into the dialog, and the Gig-o calendar will appear in your calendar list. Note that Google Calendar updates subscriptions every few hours, so changes you make in the Gig-o will take a while to be reflected there.

Subscribing in Apple Calendar: Select "New Calendar Subscription" from the "File" menu - paste the calendar address into the dialog, and a new dialog will open where you can give the calendar a useful name, etc.

Subscribing in Outlook:
1) Go to Tools - Account Settings...
2) Select the Internet Calendars tab
3) Click New...
4) Paste in the subscription address from above
5) Click Add
6) Change the Folder Name to 'Gig-o-Matic'
7) Click OK
The Gig-o calendar will show up under 'Other Calendars.'

**Comment by aaronoppenheimer** [comment]
All of the text is managed through Babel - [here](https://github.com/Gig-o-Matic/GO2/blob/05df9f50af8a2d0a9d88bd7ae374ad3ac9334aea/locale/en/LC_MESSAGES/messages.po#L736)'s the source of the calendar help strings. If you haven't used babel before I'm happy to talk you through how it works.

**Comment by prlyons** [comment]
This appears to be the v3 link to the [help strings](https://github.com/Gig-o-Matic/GO3/blob/main/locale/en-US/LC_MESSAGES/django.po)

**Comment by aaronoppenheimer** [comment]
This is actually a complicated issue. Gig-o 2 used pybabel for managing strings and jinja2 for the template engine. Django has its own tools for managing locale language files and there are some sticking points; it's not working the way it's supposed to. I will take on straightening this out (hopefully cutting out the parts we no longer need).

**Comment by aaronoppenheimer** [comment]
Fixed in https://github.com/Gig-o-Matic/GO3/pull/249. In the end, I think just regenerating the .mo (translation) files did the trick.

**Comment by bklang** [comment]
Confirmed! Thanks!
