### ISSUE TITLE
Password resets not working

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#226]
The reset password page uses a captcha (because back when it didn't, someone figure it out and a whole lot of people who didn't use the gig-o got invited to update their passwords).

The site key and secret key have been updated to match the new domain name (new.gig-o-matic.com), but the captcha form is not appearing on the page.

**Comment by aaronoppenheimer** [comment]
I do see the captcha on the password reset page - it's a v3 google "recaptcha" so it just shows up as a little captcha logo at the bottom-right of the page.

Looking at the recaptcha console today, I see the attempts from last night so it's clearly linking the new gig-o correctly. And those attempts are rated "high" which means they're not failing.

And, looking further into the error screen that shows up, the failure seems to be in sending the "reset your password" email. Is the sendgrid connection set up yet?

**Comment by bklang** [comment]
Great investgating, you are exactly right. I'm seeing the exception reported in Sentry with this message:

```
"message":"The provided authorization grant is invalid, expired, or revoked"
```

I'll try re-issuing the SendGrid API keys and make sure the sender is correct.

**Comment by bklang** [comment]
I reset the API keys and received a password reset email. I think this is resolved.

**Comment by aaronoppenheimer** [comment]
If by "great investigating" you mean "good job reading the rest of the error messages" then you're right, I'm Sherlock Holmes.

It worked for me! I agree it's resolved.
