### ISSUE TITLE
Incorrect end dates on event series

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#242]
When using "Add A Series Of Copies" checkbox, the backend creates several copies of the new gig by adjusting the date forward. If the user does not provide an end date, then all copies in the series will have the same end date, which is defaulted to the start date of the first event in the series. 

Reproduction:
* Create a new event with a start date of March 2 and no end date
* Check box to add a series and specify 4 weekly events
* Save the event
* 4 new events are created with start dates of March 2nd, 9th, 16th, and 23rd, but all 4 events have an end date of March 2nd.

Also check the end times, they may not be correct (could be related to #264?)

**Comment by aaronoppenheimer** [comment]
This was fixed at some point - if you don't provide an end date for a gig, there's no end date at all and same for copies.
