### ISSUE TITLE
Band schedule page should show more than the next 8 gigs

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#266]
For bands that have a lot of upcoming gigs (like rehearsals), 8 isn't enough to see further into the future.

**Comment by aaronoppenheimer** [comment]
There is a pagination "more..." that brings up the next 8. This replaced the old gig-o mechanism that toggled between showing 8 and showing all upcoming gigs in that bottom pane. But this could be a preference, or if someone wants to get fancy could be an infinitely-scrolling widget.

**Comment by Oscillope** [comment]
Just adding in something I just encountered - when you have more than 8 "Future Gigs" (i.e. gigs you haven't responded to) only the first 8 show up in that pane and there is no "more..." button, more just populate after you respond and refresh the page.

**Comment by aaronoppenheimer** [comment]
addressed by #314
