### ISSUE TITLE
Default band color code should not be white

### ISSUE THREAD

**Issue by aaronoppenheimer** [Gig-o-Matic/GO3#274]
On the agenda page, each gig has a colored bar on the left edge. There's a color picker on the agenda page that lets you choose a color for each band you're in to color-code the gigs and more easily distinguish between your bands.

The default color seems to be white, which looks like a display glitch when the gig is shown on a gray background, which half of them are. I suggest that "white" should mean "don't show a bar at all" (and maybe the white box in the picker should be an "X" box).

And, if a member is in only one band, they don't need to see the color-picker at all.

**Comment by bklang** [comment]
Maybe we could add a setting to the band to default their color? For example, Black Sheep would pick black, and all members would see that by default. Individual users could then override that color as desired (the current behavior)

**Comment by aaronoppenheimer** [comment]
I think that's a good idea - but still need to solve the "white looks weird" problem.

**Comment by aaronoppenheimer** [comment]
Visual problem addressed in #291
