### ISSUE TITLE
No login cookie?

### ISSUE THREAD

**Issue by aaronoppenheimer** [Gig-o-Matic/GO3#276]
Gig-o 2 has a "remember me" checkbox on the login page, which sets a cookie so you don't have to log in next time. Gig-o 3 doesn't have one. Django has support for doing it automatically but I don't see it addressed in go3/settings.py - although according to the docs, maybe session cookies are just on by default..?

**Comment by aaronoppenheimer** [comment]
This is just handled by the Django auth system.

**Comment by subrook** [comment]
It doesn't seem to be working.  I have a browser where I've had Gig-o 2 tabs open for months, and it continues to keep me logged in.  In the same browser I also have a Gig-o 3 tab I opened when one of my bands migrated two weeks ago; that tab just asked me to re-log in.  (I can open a new issue for this if needed.)

**Comment by aaronoppenheimer** [comment]
I think the default cookie age-out is two weeks. Will extend! Thanks for catching it.

**Comment by aaronoppenheimer** [comment]
addressed in #406
