### ISSUE TITLE
Should migrate to django-q2

### ISSUE THREAD

**Issue by aaronoppenheimer** [Gig-o-Matic/GO3#286]
It turns out development on django-q stopped a while ago, but there's a [fork under active development](https://github.com/django-q2/django-q2). Should just require a change to requirements.txt - looks like a drop-in replacement.

**Comment by bklang** [comment]
This was already done with the upgrade to Django 4.2

https://github.com/Gig-o-Matic/GO3/blob/main/requirements.txt#L15
