### ISSUE TITLE
Schedule view doesn't show gig times

### ISSUE THREAD

**Issue by Oscillope** [Gig-o-Matic/GO3#294]
Gig call time doesn't show up under the date in the schedule view. I initially thought this was  #144 but it happens even on gigs without end times so I figured it's worth its own report.
![20240311_18h10m49s_grim](https://github.com/Gig-o-Matic/GO3/assets/2652071/0724e0e8-945f-4f02-bf3f-200776b246bb)
![20240311_18h10m55s_grim](https://github.com/Gig-o-Matic/GO3/assets/2652071/08c88c11-9d77-4443-a708-33b8744bd250)

**Comment by aaronoppenheimer** [comment]
Huh. Who wrote this thing? There's a new preference for members to turn on/off showing time on the agenda page. But there's no UI to set the preference, and even if it's set to "true" the template code is messed up and doesn't work.

It's an easy thing to fix. Question for the group: is that feature worth having?

**Comment by aaronoppenheimer** [comment]
Oh, now I see. A gig with no start time, which is an all-day event, shows that it starts at "midnight." And then when you go back and edit it, it shows a start time of 12:00am. That's too bad.

One solution is to add a field to gigs "all_day" and a save-triggered signal that sets it if the gig has a start time of midnight. Or maybe there should just be a checkbox in the gig edit page marked "all day event" - if it's marked, it hides the time fields. Then the template can make a choice of how to display it based on the field.

**Comment by Oscillope** [comment]
> Huh. Who wrote this thing? There's a new preference for members to turn on/off showing time on the agenda page. But there's no UI to set the preference, and even if it's set to "true" the template code is messed up and doesn't work.
> 
> It's an easy thing to fix. Question for the group: is that feature worth having?

Personally, I can't think of a reason someone _wouldn't_ want the time on the agenda page. But if there's already an option wired up, I don't think it'd hurt.

**Comment by aaronoppenheimer** [comment]
The schedule page shows times, and there's no way to turn it off but nobody's complaining!
