### ISSUE TITLE
Freeform gig time values are silently normalized to midnight

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#298]
Our band frequently uses freeform time values like "2 hours later" or "not before 11:30", or "??" to indicate that some part of the gig timing info is still TBD.

In GO3, if we input an unrecognized time like that, it's silently normalized to 12:00am after saving. (This also happened during import.)

It's a major problem that this information is silently discarded - if it's going to be discarded, you shouldn't be able to save the page until it's fixed.

However, our strong preference is that this data is NOT normalized to times, but that rather it continues to allow use of freeform text values like this.

**Comment by nocturne-mit** [comment]
We also frequently used values like "3:00pm?" to indicate when times were approximate. Because the info is still useful, but it's important to indicate when it's not exact.

I suppose we can use the "Date Notes" field for all this imprecise info, but also it would be great if there were a meaningful empty/NULL time that didn't show up as "12:00 AM" because we do occasionally have gig end times at midnight.

**Comment by nocturne-mit** [comment]
Your policy of normalizing time values seems fine, given the "time notes" field.

I agree that an "all day" checkbox would be a decent option. It's common for us to not have any timing info at all when we're first checking member availability, and "all day" maps to that.

We did not rely heavily on the old gig-o calendar feed, so the freeform times were not a huge deal. We also have a hand-maintained google calendar, which also allowed us to do things like create individual calendar events for each of 5 different performance times and places during a busy HONK weekend, without needing to have separate Gig-O gigs for each set.

**Comment by bklang** [comment]
This is fixed in #379. Thanks for your input!
