### ISSUE TITLE
Allow freeform (or multiple-choice) gig leaders

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#299]
Our band frequently has co-leaders for a single gig. In GO2, "Leader" was freeform, so this worked fine.

It would be great if the "Leader" field continued to support some way to indicate more than one leader.

**Comment by aaronoppenheimer** [comment]
It's not freeform in GO2 - it's a popup and it's prepopulated with whoever is creating the gig. Do you see it freeform?

Allowing multiple contacts is an interesting idea. The original intent is the "contact" is the person who is in touch with the venue so would be the best source of information on the gig. I can see that it could be more than one person.

**Comment by Oscillope** [comment]
> It's not freeform in GO2 - it's a popup and it's prepopulated with whoever is creating the gig. Do you see it freeform?

The "contact" field is a dropdown in GO2, but the "leader" field is freeform (at least, I see it that way as well). On GO3 they're both dropdowns.

**Comment by aaronoppenheimer** [comment]
Oh, you're right! Yes, there's no reason the "leader" can't be a freeform field.

**Comment by bklang** [comment]
Done in #328
