### ISSUE TITLE
gig_detail.html should display weekdays

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#302]
In GO2, the Gig Info page would display weekdays in addition to the date (e.g. "Friday, August 2, 2024").

Displaying the weekday on this page is a valuable checksum / sanity-check that helps any flaky bandmates correctly understand which date is under consideration.

In the GO3 gig_detail.html, the weekday is not displayed (e.g. "08/02/2024"). I think it's worth displaying the weekday here.

**Comment by aaronoppenheimer** [comment]
this is done
