### ISSUE TITLE
Schedule page "more..." should be more obvious

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#305]
My band has more than 10 events in GO3. When I realized some were missing, it took me a few moments to notice the "more..." button at the bottom of the page.

Even today, knowing that the button exists, I keep being tricked by the fact that it's hiding some of our gigs - the button is relatively small and subtle in a desktop browser.

I'm no UX designer, but could the button be made more obvious somehow? Outlining it in a bright color (orange? blue?) might help, or maybe making the button larger, or adding some obvious arrow icons by/in the button suggesting motion or expansion?

**Comment by nocturne-mit** [comment]
That said, my preference would be to always display all gigs on this page, but I understand if that is undesirable due to scalability/performance concerns.

**Comment by annaballasiotes** [comment]
I agree with this! Preference is to display all gigs.

**Comment by aaronoppenheimer** [comment]
The people have spoken. Or I'll make it an option to just show a few - that's basically how it was in go2.

**Comment by bklang** [comment]
Related to #266

**Comment by aaronoppenheimer** [comment]
addressed by #314
