### ISSUE TITLE
GO3 migration discards non-normalized time data

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#306]
When migrating from GO2, all time values are normalized into actual times, and the original data is discarded. For bands that have a lot of gigs with freeform time values, this is going to make for a lot of lost information / manual repairs.

It might be more helpful if these freeform values were preserved verbatim in the "Date Notes" field, when their normalized value is 12:00AM. For example, set time "between 2-4pm" could show up in the date notes as "Set time: between 2-4pm".

**Comment by bklang** [comment]
@aaronoppenheimer I'll need your help with this. It looks like they are coming to me already converted to a date type in the JSON. Could you preserve the original string value in a separate set of fields?

**Comment by aaronoppenheimer** [comment]
Yes, will do.

**Comment by bklang** [comment]
This is done, as best we can. Thanks for the feedback
