### ISSUE TITLE
Band "public profile" link does not work

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#310]
[This link](https://new.gig-o-matic.com/band/blacksheepensemble) is advertised on the Band profile page, but leads to a 404 (was probably not implemented on the new site).

<img width="597" alt="Screenshot 2024-03-13 at 12 23 27 AM" src="https://github.com/Gig-o-Matic/GO3/assets/167131/2f5b25e0-8166-46f6-8628-fb2000c8a641">

**Comment by aaronoppenheimer** [comment]
Two problems I see:

- first, the url is new.gig-o-matic.com/band/[bandname] but in the band urls.py it is implemented as "xxx/pub/[bandname]"
- second, that link doesn't work either, though it should call some code in helpers.py that just redirects to "/" if there's an error...but that's not happening.

The "public page" is just the same as the band detail page but it only shows some of the information. If you're not a member of a band, or you're not logged in, that's what you see on a band page. If you open a private window and navigate to "https://new.gig-o-matic.com/band/5/" you should see a pared-down band page - that's all the "public band page" is supposed to do.
