### ISSUE TITLE
Member ordering in a section varies from gig to gig?

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#312]
Currently the Gig Info pages for these two gigs have different orders for members in our "Middle Voices" and "Drums" sections. I can't find any obvious pattern as to the difference.
https://new.gig-o-matic.com/gig/262/
https://new.gig-o-matic.com/gig/259/
<img width="142" alt="Screenshot 2024-03-13 at 6 50 33 PM" src="https://github.com/Gig-o-Matic/GO3/assets/5275151/88995125-575f-49d8-b61e-d64b01349886">
<img width="135" alt="Screenshot 2024-03-13 at 6 51 09 PM" src="https://github.com/Gig-o-Matic/GO3/assets/5275151/f47fe97c-801e-404d-aba4-0bc781c862ba">

**Comment by aaronoppenheimer** [comment]
Thanks for reporting, Eric!

This is the same issue as #282 - closing this in favor of that.
