### ISSUE TITLE
Change in user experience for occasional members?

### ISSUE THREAD

**Issue by hellomslady** [Gig-o-Matic/GO3#322]
_Expectation:_
As an occasional member I wasn't expecting to see gigs on my home page (usually occasional members were not invited) or to receive emails when gigs are added for that band.

_Current State:_
* I can see approx. every event for a band where I am an occasional member.
* I am prompted to submit my attendance both via the home page and via email.
* I don't think I appear on the event when others in the band look at the gig page?
---
_Example:_
https://new.gig-o-matic.com/gig/262/ - HONK!TX

I show up in the drum section on my view
<img width="426" alt="Screenshot 2024-03-15 at 12 39 00 PM" src="https://github.com/Gig-o-Matic/GO3/assets/163568451/4eb05c9a-7907-4f38-8bb1-d09e230cd6df">

Also shows up on my home page (along with all other events for that band). These did not show up pre-transition.
<img width="636" alt="Screenshot 2024-03-15 at 1 01 58 PM" src="https://github.com/Gig-o-Matic/GO3/assets/163568451/c8102f56-437e-43eb-8b5a-878ca2883d5c">

Based on screenshots from https://github.com/Gig-o-Matic/GO3/issues/312 I don't believe I show up in the view for others (kinda squinting, but I don't see an "E" in the drum section & number of members doesn't match).

Similarly, I see another occasional member went through and actively "X"ed every event, so I think this may have happened to multiple folks?

---
Anyway, excited to be trying out this new experience! THANK YOU for making this happen. Happy to play around with settings or anything else.

**Comment by aaronoppenheimer** [comment]
Confirmed this is broken. Thanks for the bug report! Will fix...

**Comment by aaronoppenheimer** [comment]
To verify - you also got emails for bands you don't think you should have?

**Comment by hellomslady** [comment]
Correct - for the same band where I am an occasional member, I received both a mass set of emails (I am guessing from the migration) on March 11th, as well as further updates.

For example : Gig https://new.gig-o-matic.com/gig/275/

<img width="1386" alt="Screenshot 2024-03-15 at 3 56 04 PM" src="https://github.com/Gig-o-Matic/GO3/assets/163568451/46bd0137-b57e-4e54-a007-1e0c555a7ccc">

<img width="638" alt="Screenshot 2024-03-15 at 3 55 34 PM" src="https://github.com/Gig-o-Matic/GO3/assets/163568451/6d5a628f-d122-4197-b3df-87236a1c817d">

**Comment by aaronoppenheimer** [comment]
OK - thanks!
