### ISSUE TITLE
Grid view showing gigs in wrong order

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#329]
It looks like it is sorting on last-updated date instead of event date (screenshot is local test data)

<img width="1061" alt="Screenshot 2024-03-16 at 12 12 35 PM" src="https://github.com/Gig-o-Matic/GO3/assets/167131/8e8e035b-2d70-48d8-82a5-1fd25916b1be">

**Comment by aaronoppenheimer** [comment]
argh
