### ISSUE TITLE
thoughts about gig times

### ISSUE THREAD

**Issue by aaronoppenheimer** [Gig-o-Matic/GO3#337]
As has been noted, the time implementation in the gig-o is a little messy. How should we fix it? @bklang @nocturne-mit

The old gig-o ("go2") used separate data and time files in its database representation. Dates were stored as dates, but times were stored as text. This made it possible for a band to declare the gig start time as "4ish" or whatever they wanted, which was cool but messed up the calendar feed - if the feed couldn't parse a time, it just declared the gig an all-day event. Maybe that was fine; maybe not.

The new gig-o ("go3") combines the date and times into three datetimes in the database. This means the date/times are always comparable and sortable, but we've lost the ability to put in "spongy" times - for that purpose there is a "time notes" text field. But it's not very well implemented (or thought out!) so the times get messed up. Even when you want a whole-day event, the times show up as "midnight" which isn't right.

So how to think about it?

- It seems like a good idea to have gig dates and times be real datetimes when possible
- It seems like a good idea to be able to explicitly say "this is an all day" (or "multi day") event
- Gigs should be able to have blank times which might make them show up as all-day events but not actually mean "starts at midnight"
- Gigs should have a comment field like "time notes" - if there's no actual time specified, the time notes show up someplace instead. So if I leave the call, set, and end times blank but put "after lunch" in the notes field, "after lunch" should show up on the agenda page as the time.

Questions

- Do we have a switch on the gig form to pick between "specific times" "not sure yet" and "all day"? If you don't say "specific times" the time fields disappear? If you say "all day" you also get an "end date" field so you can make it multi-day?
- What if you don't know the *date* exactly? Should we deal with that, or do we say you have to know at least the day? Over the years some people have asked for a feature that would let people give preferences for the date (like, it could be one of three days - pick one). Is that something we can think about? (I have thought about a more general "poll" system, and in fact the weigh-in-on-a-gig mechanism would be easy to convert to a poll - it basically *is* a poll.)

Implementation Notes
- If we have the ability to leave times blank, we don't want to simply store them as "midnight" - we also need a boolean "has a start time" so we can discern between "has a time and it's midnight" and "doesn't have a time"

**Comment by nocturne-mit** [comment]
I think a multi-mode time interface would be good. I'm not sure what would be clearest to gig-editors and gig-viewers. Handling this as a visible radiobutton choosing specific/uncertain/allday seems a little clunky to me as a user, but as a non-UX person I don't have any better ideas for how this might look.

For our band, we use the gigo to get a firm commitment of member availability for unconfirmed gigs. So I don't think our usage model would benefit from uncertain gigo-event dates.

Date/time selection polls might be occasionally handy in the future (if they're flexible enough) though I'm more interested in core GO3 functionality at the moment.

**Comment by bklang** [comment]
> * It seems like a good idea to have gig dates and times be real datetimes when possible
> 
> * It seems like a good idea to be able to explicitly say "this is an all day" (or "multi day") event
> 
> * Gigs should be able to have blank times which might make them show up as all-day events but not actually mean "starts at midnight"
> 
> * Gigs should have a comment field like "time notes" - if there's no actual time specified, the time notes show up someplace instead. So if I leave the call, set, and end times blank but put "after lunch" in the notes field, "after lunch" should show up on the agenda page as the time.

For the record, I agree with all 4 of these points



> * Do we have a switch on the gig form to pick between "specific times" "not sure yet" and "all day"? If you don't say "specific times" the time fields disappear? If you say "all day" you also get an "end date" field so you can make it multi-day?

I think keep it simple: a single checkbox for "time uncertain" can hide the time input fields and treat the event (for calendar purposes) as "all day". If "time notes" are provided, then show those where appropriate.

> * What if you don't know the _date_ exactly? Should we deal with that, or do we say you have to know at least the day? Over the years some people have asked for a feature that would let people give preferences for the date (like, it could be one of three days - pick one). Is that something we can think about? (I have thought about a more general "poll" system, and in fact the weigh-in-on-a-gig mechanism would be easy to convert to a poll - it basically _is_ a poll.)

I think this is a cool idea, but adds a LOT of complexity for something that already has a lot of input boxes (gigs). I'd rather see this use case handled with a polling system.

> * If we have the ability to leave times blank, we don't want to simply store them as "midnight" - we also need a boolean "has a start time" so we can discern between "has a time and it's midnight" and "doesn't have a time"

Agree. In my mind this is a single additional column on the gig table, and not an attempt to split out the date and time columns.

To your comment about parsing textual times: Personally, I'm not a big fan of fuzzy behavior like that. It can do really unexpected things, like inferring AM when you mean PM.  Users end up with their own sort of belief system and they develop their own tricks to "hack" the software to get some behavior we never specified. I much prefer that we are specific about what we want: if we want a time, ask for a time and ensure we get good data. If we want unstructured data, then get it and don't try to infer structure.

**Comment by aaronoppenheimer** [comment]
> To your comment about parsing textual times: Personally, I'm not a big fan of fuzzy behavior like that. It can do really unexpected things, like inferring AM when you mean PM. Users end up with their own sort of belief system and they develop their own tricks to "hack" the software to get some behavior we never specified. I much prefer that we are specific about what we want: if we want a time, ask for a time and ensure we get good data. If we want unstructured data, then get it and don't try to infer structure.

That's totally fair. So maybe we're circling:

- Allow the time fields to *only* accept actual times (either from the widget or by typing in something that can be parsed) or they can be left blank. If they're all blank, it's an all-day event by default.
- Make the "this is an all day gig" checkbox hide the time fields.

Is that all the UI needs? Then under the covers there are columns to describe the state of the times (they're real, they're unset).

**Comment by aaronoppenheimer** [comment]
**Just here for my notes.**

This seems to be working in #379 but I'm worried about the data migration breaking things. I think these are the cases I need to work on, based on how go3 currently handles date.

The gig...
- ...has only a date
  - if the date is midnight (local to the band), it's an all-day event
  - if the date is 12:56, this is an all-day event - it's the weird timezone-conversion artifact
  - if the date is not midnight, the time is a real "call time"
- ...has a date and an enddate or has a date and calldate but no enddate
  - if the date and enddate (calldate) are different dates (ignoring times)
    - this is an all-day (or multi-day) event, so set the flag and strip the times out of the date, setdate, and enddate
  - if the date and enddate (calldate) are the same date
    - if any of the times are not midnight and not 12:56, consider it a real time and set the right flag True
- ...has a date, calldate, and enddate
  - if any of the times are not midnight and not 12:56, consider it a real time and set the right flag True

Assumes any "midnight" time is not really "midnight" but rather "didn't set a time."

Plan
- Make a fixture with each of these cases
- Rollback the migration, import the fixture, migrate
- Examine each of the cases

You can theoretically test migrations with pytest but since is a one-off I don't think I care.

**Comment by bklang** [comment]
Fixed in #379
