### ISSUE TITLE
User logins should not be case sensitive

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#338]
I've had a handful (5?) of emails from people saying that they are unable to log in after resetting their password. Until now, I never had a good explanation, but one person just told me that it worked when they used all lower case.  We should force all emails to be lower case all the time to prevent this confusion.

**Comment by aaronoppenheimer** [comment]
It seems like we need to store the email as lowercase, and need to make it lowercase when it gets entered into the login form. The former can be done with a pre_save signal on the member; the latter can be done by overriding the login form as seen [here](https://stackoverflow.com/questions/55369645/how-to-customize-default-auth-login-form-in-django).

Maybe there's some other way to do it, though - some discussion [here](https://stackoverflow.com/questions/50895643/removing-case-sensitivity-from-email-in-django-login-form).

**Comment by bklang** [comment]
> It seems like we need to store the email as lowercase, and need to make it lowercase when it gets entered into the login form. The former can be done with a pre_save signal on the member; the latter can be done by overriding the login form as seen [here](https://stackoverflow.com/questions/55369645/how-to-customize-default-auth-login-form-in-django).

This sounds pretty reasonable to me

**Comment by aaronoppenheimer** [comment]
Actually, maybe we only have to make sure that the email is converted to lowercase in two places - one in the signup form and one in the "invite other people" form.

**Comment by aaronoppenheimer** [comment]
One thing I find is that, according to the relevant standard, the "left of the @" part of emails are case-sensitive. aaron@AARON.com and aaron@aaron.com are the same, but aaron@aaron.com and Aaron@aaron.com are acceptably different.

Practically, though, I still thing we should just lowercase everything. Agreed @bklang ?

**Comment by bklang** [comment]
> Practically, though, I still thing we should just lowercase everything. Agreed @bklang ?

Yep, agree. In my experience no reasonable system tries to issue two different people the same username with different cased letters.

**Comment by aaronoppenheimer** [comment]
Fixed in #348
