### ISSUE TITLE
GO3 should be visually distinct from GO2

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#340]
I've had several users report issues "not working in the new Gig-O", but when they send a screenshot, they are in the old Gig-O.

**Comment by kalebabebe** [comment]
Guess the heart wasn't enough! Changing the banner color might be most straight forward approach

<img width="1033" alt="image" src="https://github.com/Gig-o-Matic/GO3/assets/95705454/fd011ff0-5fff-45b5-9d83-e504b98dbc3c">

**Comment by bklang** [comment]
> Guess the heart wasn't enough! Changing the banner color might be most straight forward approach
> 
> 
> 
> <img width="1033" alt="image" src="https://github.com/Gig-o-Matic/GO3/assets/95705454/fd011ff0-5fff-45b5-9d83-e504b98dbc3c">
> 
> 

You read my mind! I too imagined the banner in green to match the Gig-O icon. I'll have a go at it this evening.
