### ISSUE TITLE
Inviting an "alumni" member doesn't work

### ISSUE THREAD

**Issue by aaronoppenheimer** [Gig-o-Matic/GO3#343]
- have a member join a band
- remove the member from the band using the "remove from band" in band admin panel
- invite the member back to the band using "invite"
- see message that user is already in the band

"Alumni" members should just be set back to "confirmed" if this happens, I think.

**Comment by bklang** [comment]
> "Alumni" members should just be set back to "confirmed" if this happens, I think.

Maybe put them back into the "invited" state, so they can decide whether to accept the invitation?

**Comment by bklang** [comment]
Fixed in #359
