### ISSUE TITLE
Icons broken?

### ISSUE THREAD

**Issue by aaronoppenheimer** [Gig-o-Matic/GO3#350]
At the bottom of the band page, the two collapsible panes should have "toggle" icons that now seem broken:

<img width="229" alt="image" src="https://github.com/Gig-o-Matic/GO3/assets/2896310/bcb3b8d5-e823-420d-a9b0-ebb09ccdfd03">

Maybe has to do with fontawesome deciding we've gone over the free tier?

**Comment by bklang** [comment]
I've seen this intermittently both on the live site and locally. I can't tell what is causing it. I did not see any errors in the network tab of the browser tools.

**Comment by aaronoppenheimer** [comment]
Those particular icons are defined in the CSS, using a FontAwesome font family. None of the other icons work that way.
