### ISSUE TITLE
Restrict gig availability options

### ISSUE THREAD

**Issue by SethPate** [Gig-o-Matic/GO3#362]
I'd like to reduce this to two options: available and not available. Can this be done?
<img width="176" alt="image" src="https://github.com/Gig-o-Matic/GO3/assets/17327269/68c4aab7-c140-4624-834a-a8f1876692cf">

**Comment by aaronoppenheimer** [comment]
Yes! On the band page, click 'edit' - at the very bottom is an option "simple planning" which will only give the options "Definitely" "Don't Know" and "Can't Do It."

**Comment by SethPate** [comment]
Oh cool, thanks! I thought that might've been it -- maybe helpful to have a tooltip or little explainer nearby.
