### ISSUE TITLE
Duplicating gigs does not copy dates OR times

### ISSUE THREAD

**Issue by nocturne-mit** [Gig-o-Matic/GO3#382]
When I duplicate a gig, I always want the newly-created gig to have the same time info pre-filled in the gig-creation form (call/start/end and Date Notes). It would also be fine with me if the date values gets copied into the new as well. (Although, honestly, I might find it less error-prone if the dates were actually blank and I was not allowed to submit the gig until I filled them in. But that's kind of a different feature request.)

I see this behavior when duplicating https://new.gig-o-matic.com/gig/261/

**Comment by aaronoppenheimer** [comment]
Hi Eric - you're right, dates/times are specifically not copied over. I don't know why, the old gig-o does what you suggest. Will fix!

**Comment by aaronoppenheimer** [comment]
addressed in #398
