### ISSUE TITLE
Cancelled gigs not hidden

### ISSUE THREAD

**Issue by PaulieGregory** [Gig-o-Matic/GO3#397]
Hi Aaron and Ben
A Non critical issue:

When a gig is canceled  it still shows up in the “weigh in“ list if you haven’t chimed in yet. The only way to get it off the upper list is to go into the gig and select an option, any option.  Then it moves to the “upcoming gig” list.

**Comment by aaronoppenheimer** [comment]
Huh, I'm not seeing this behavior.

How it should work: There's a "hide cancelled gigs" preference in your profile that hides canceled gigs on the agenda page completely; if it's not set to hide them they're always shown but marked "canceled" whether you have previously weighed in or not.

This is working properly for me. How is that preference set for you?

(You do raise a different point - if the gig is canceled there shouldn't be any plans shown in the gig page.)

**Comment by PaulieGregory** [comment]
Oops. My bad on this one. Didn’t remember that setting and didn’t notice it
when I reset my profile. Right now.

Sorry 😳

P

(Might a band leader want to see cancelled gigs in case a gig is
un-cancelled. Should thy have their own section?)

**Comment by aaronoppenheimer** [comment]
Maybe! I'm thinking about "agenda page customization" and "split out cancelled gigs into their own box" could be an option.

**Comment by PaulieGregory** [comment]
What happened to "I am done with the giggo"? 😃

**Comment by PaulieGregory** [comment]
It's good to have a hobby

**Comment by aaronoppenheimer** [comment]
closing in favor of #385
