### ISSUE TITLE
Calendar help page is missing part of URL

### ISSUE THREAD

**Issue by jontmoran** [Gig-o-Matic/GO3#409]
On the calendar help page, the "https://new.gig-o-matic.com" prefix is missing from the calendar URL; e.g., mine says:
>First, copy the subscription address. Your personalized address is:
>
>/member/calfeed/61886fa6-1550-48cd-94c1-7b76b1bd88ed

**Comment by aaronoppenheimer** [comment]
Great catch! I've addressed this (pr #410) and will deploy the update shortly.

**Comment by aaronoppenheimer** [comment]
Done!
