### ISSUE TITLE
Change occasionals default 

### ISSUE THREAD

**Issue by PaulieGregory** [Gig-o-Matic/GO3#416]
Hi

I am passing on a request for two bands to make the “Also send update to occasional members” default to true (checked) or make it a configurable option. Both bands have occasional members who attend occasionally (duh) but never hear about the gig if the organizer neglects to check the box. I don’t think this function worked on the old gigo and don’t was never an issue. 

Thanks

Paul

**Comment by aaronoppenheimer** [comment]
Hi Paul - I think "also send update to occasional members" does default to true. If you unset it when you edit the gig, it will remain unset unless you edit the gig again and set it. But I think a new gig should always default to "it's checked."
