### ISSUE TITLE
Gigs disappearing

### ISSUE THREAD

**Issue by PaulieGregory** [Gig-o-Matic/GO3#417]
Oops

seems gigs are disappearing as soon as their gig time is reached. They used to disappear the next day. Means we can’t see gig night info after the gig time.  Was that intentional?

Paul.

**Comment by aaronoppenheimer** [comment]
Ah, can adjust!

**Comment by aaronoppenheimer** [comment]
fix should be up in a few minutes - thanks Paul!

**Comment by PaulieGregory** [comment]
THANK YOU!!!
