### ISSUE TITLE
From logged off state clicking on "Gig info page is here" link from email does not direct to gig page after log-on

### ISSUE THREAD

**Issue by kalebabebe** [Gig-o-Matic/GO3#453]
Clicking on "Gig info page is [here](https://www.gig-o-matic.com/gig/952/)" link when logged off does not direct user to gig after logon

<img width="1276" alt="image" src="https://github.com/Gig-o-Matic/GO3/assets/95705454/074bf4e6-aa48-4f54-bcfd-c5025c35626c">

HAR file in case that's helpful- [www.gig-o-matic.com.har.zip](https://github.com/Gig-o-Matic/GO3/files/15079721/www.gig-o-matic.com.har.zip)

**Comment by annaballasiotes** [comment]
+1 to this — the “gig info” page from email announcements and updates has been leading to old gig-o for some reason // not leading to the right place!
