### ISSUE TITLE
"Anyone can manage gig" settings not saving?

### ISSUE THREAD

**Issue by bklang** [Gig-o-Matic/GO3#459]
Reported via email: 
> Hmm - and when I looked just now the "anyone can manage gigs" box was AGAIN unchecked.  I  rechecked it, got out of the Edit page, went back to Edit and it was again unchecked! So changing it does not "stick" even after saving the config change.

**Comment by aaronoppenheimer** [comment]
That is strange - it works for me. Maybe they're using the "back" button to back to the edit page, instead of hitting "edit" again - when I do that I see this behavior.

**Comment by aaronoppenheimer** [comment]
Haven't heard anyone complaining about this - I suspect they were using "back" instead of save.
