### ISSUE TITLE
Need some clarification 

### ISSUE THREAD

**Issue by PaulieGregory** [Gig-o-Matic/GO3#469]
Hi Y'all 

A bewilderment that we need to clear up:

Our understanding:
- When creating a gig, to have the "occasionals" see the gig at all, you need to check the "Also send update to occasional members" check box ( I wish this could be the default but one thing at a time).
- While this is checked they see the gig in their "schedule" and will receive all email notifications when changes are made to the gig as long as the "Email members about change" is checked.

But
- When making a minor change (fixing typo in a set list for instance) the inclination is to uncheck both "Also send update to occasional members" and "Email members about change" because the editor doesn't want to flood the members with trivial emails.
- Does this take the "occasionals" off of the gig?
- If you just uncheck the "Email members about change" do the "occasionals" get the notification but nobody else as implied by "Also send update to occasional members"?
- Should the wording for the first option be something like "Include occasional members in this gig."?

Enlighten us please masters.

Paul

**Comment by aaronoppenheimer** [comment]
Hi Paul,

- your understanding is correct
- yes, if you uncheck 'send update to occasional members' you will uninvite occasional members, meaning they won't get future updates and won't see the gig in their schedule (except those that have already weighed in - their plans stay as they were)
- if you uncheck 'email members' nobody gets the notification
- yes, that's better wording!

A

**Comment by PaulieGregory** [comment]
Perfect: Thanks so much

**Comment by aaronoppenheimer** [comment]
Also - "invite occasionals" should be "true" by default for new gigs. Is that not what you see?

**Comment by aaronoppenheimer** [comment]
messaging updated in #471

**Comment by PaulieGregory** [comment]
Well damn it is. That must have just been a thing during the transfer with
that option going to false. Sorry bout that.
