### ISSUE TITLE
Feature Request: Duplicating an Archived Gig

### ISSUE THREAD

**Issue by that-jill** [Gig-o-Matic/GO3#534]
Putting this request in here from Alicia Cardillo (one of the Seed & Feed managers), who doesn't have a github login:

"Right now, I can only duplicate future gigs. I would like the capability to duplicate an archived gig." 

It looks like all this may need is a link in [gig_detail_archived.html](https://github.com/Gig-o-Matic/GO3/blob/2c41bcb3edfe9bd174850e0903389b06065d5608/templates/gig/gig_detail_archived.html) ? @aaronoppenheimer @bklang is there any other reason that archived gigs cannot be duplicated?

**Comment by aaronoppenheimer** [comment]
hi Jill - you're probably right, and there's no reason not to be able to dupe an archived gig. Nobody has ever asked to do that before!

Looking at it all, I'm not sure why there are different templates for archive-gigs and not-yet-archived gigs. In gig-o 2 they were quite different and that structure was clearly just ported into GO3 by whoever did it (which was me), but there's no reason they can't use the same template and just turn off features unavailable in archived gigs. I'll take a look.

**Comment by aaronoppenheimer** [comment]
addressed in #1132 - can now duplicate archived gigs (and both archived and unarchived gigs use the same template).
