### ISSUE TITLE
Please clarify "hide" (gig feed vs calendar) UI

### ISSUE THREAD

**Issue by kirkjerk** [Gig-o-Matic/GO3#544]
UI improvement -
I got confused by the "hide from calendar" button (near the bottom) and the "hide from public gig feed" (which is higher up , and I think I missed it there)

Touching base with Aaron he explained what I missed but thought I could file a ticket for clarity, he wrote

` So that's what should be fixed - the "hide from public feed" should be moved down on the page, and the "hide from calendar" should be clarified. `

Looks like an easy fix, but isn't that what the person not having to fix it always says ? :-D 

(And thanks as always)

**Comment by aaronoppenheimer** [comment]
addressed in #545
